//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETCoreJsonMapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NETCoreJsonMapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A .NET Core 3.0 project to convert one JSON formatted file to another based on a given source and target classes loaded dynamically..
        /// </summary>
        internal static string CMD_APP_DESC {
            get {
                return ResourceManager.GetString("CMD_APP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A full path to the directory from which all JSON formatted files will be processed..
        /// </summary>
        internal static string CMD_INPUT_DESC {
            get {
                return ResourceManager.GetString("CMD_INPUT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given input directory: &apos;{0}&apos; does not exists.\n.
        /// </summary>
        internal static string CMD_INPUT_VALIDATE_ERROR_NOT_EXIST {
            get {
                return ResourceManager.GetString("CMD_INPUT_VALIDATE_ERROR_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A full path to the directory where all outputed JOSN formatted files will be saved..
        /// </summary>
        internal static string CMD_OUTPUT_DESC {
            get {
                return ResourceManager.GetString("CMD_OUTPUT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a given output directory: `{0}&apos;. An error has occurred: &apos;{1}&apos;..
        /// </summary>
        internal static string CMD_OUTPUT_VALIDATE_ERROR_CREATE_DIR {
            get {
                return ResourceManager.GetString("CMD_OUTPUT_VALIDATE_ERROR_CREATE_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output directory was defined..
        /// </summary>
        internal static string CMD_OUTPUT_VALIDATE_ERROR_NOT_SET {
            get {
                return ResourceManager.GetString("CMD_OUTPUT_VALIDATE_ERROR_NOT_SET", resourceCulture);
            }
        }
    }
}
