//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETCoreJsonMapper.Commons.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NETCoreJsonMapper.Commons.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if a given JSON file&apos;s key set matches the property set of a class with the fully qualified name &apos;{0}&apos;..
        /// </summary>
        internal static string LOG_VERBOSE_VALIDATE_JSON_STRING {
            get {
                return ResourceManager.GetString("LOG_VERBOSE_VALIDATE_JSON_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A class with the fully qualified name &apos;{0}&apos; has the following set of properties that are marked by a JsonAttribute: &apos;{1}&apos;..
        /// </summary>
        internal static string LOG_VERBOSE_VALIDATE_JSON_STRING_CLASS_PROPERTY_SET {
            get {
                return ResourceManager.GetString("LOG_VERBOSE_VALIDATE_JSON_STRING_CLASS_PROPERTY_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the given JSON file the following key names was found: &apos;{0}&apos;..
        /// </summary>
        internal static string LOG_VERBOSE_VALIDATE_JSON_STRING_KEY_SET {
            get {
                return ResourceManager.GetString("LOG_VERBOSE_VALIDATE_JSON_STRING_KEY_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inputed JSON content from a file could NOT be parsed because it does NOT match a targeted class. The targeted class has less properties that the given JSON file. Missing properties: &apos;{0}&apos;..
        /// </summary>
        internal static string LOG_VERBOSE_VALIDATE_JSON_STRING_SOURCE_KEY_SET_MISMATCH {
            get {
                return ResourceManager.GetString("LOG_VERBOSE_VALIDATE_JSON_STRING_SOURCE_KEY_SET_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inputed JSON content from a file could NOT be parsed because it does NOT match a targeted class. the targeted class has more properties that the given JSON file. Additional properties that prevents from valid key-property mapping are: &apos;{0}&apos;..
        /// </summary>
        internal static string LOG_VERBOSE_VALIDATE_JSON_STRING_TARGET_KEY_SET_MISMATCH {
            get {
                return ResourceManager.GetString("LOG_VERBOSE_VALIDATE_JSON_STRING_TARGET_KEY_SET_MISMATCH", resourceCulture);
            }
        }
    }
}
